//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMFS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bmfsEntities : DbContext
    {
        public bmfsEntities()
            : base("name=bmfsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<primaryinvestigatoryear> primaryinvestigatoryears { get; set; }
        public virtual DbSet<uploadedfile> uploadedfiles { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
