//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class primaryinvestigatoryear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public primaryinvestigatoryear()
        {
            this.files = new HashSet<file>();
        }
    
        public byte Year { get; set; }
        public string PrimaryInvestigatorID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual user user { get; set; }
    }
}
